SIZE = W, H = 800, 700
FPS = 60

DIRECTION_UP = "_up"
DIRECTION_DOWN = "_down"
DIRECTION_RIGHT = "_right"
DIRECTION_LEFT = "_left"
DIRECTIONS = (DIRECTION_UP, DIRECTION_DOWN, DIRECTION_RIGHT, DIRECTION_LEFT)